"use client";

import { useEffect, useState } from "react";
import { BellRing, Plus, Radio, Save, Trash2 } from "lucide-react";
import { can } from "@/lib/auth";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase/client";
import { useCurrentProfile } from "@/lib/use-current-profile";

type Announcement = { id?: string; title:string; body:string; badge?:string|null; priority:number; active:boolean; published_at?:string|null };
const DEMO: Announcement[]=[{title:"إعلان تجريبي",body:"عدّل هذا النص لتجربة شكل نظام الإعلانات.",badge:"تنبيه",priority:10,active:true,published_at:new Date().toISOString()}];

export default function AnnouncementManager(){
  const {profile,loading:accessLoading}=useCurrentProfile(); const authorized=Boolean(profile&&(profile.is_owner||can(profile,"manage_announcements"))); const configured=isSupabaseConfigured(); const [items,setItems]=useState<Announcement[]>(DEMO); const [saving,setSaving]=useState<number|null>(null);
  async function load(){const s=getSupabase();if(!s)return;const {data}=await s.from("announcements").select("*").order("priority",{ascending:false}).order("published_at",{ascending:false});setItems((data??[]) as Announcement[]);} useEffect(()=>{if(configured)load();},[]);
  function patch(i:number,v:Partial<Announcement>){setItems(r=>r.map((x,n)=>n===i?{...x,...v}:x));}
  function add(){setItems(r=>[{title:"إعلان جديد",body:"",badge:"إعلان",priority:0,active:true},...r]);}
  async function save(item:Announcement,i:number){if(!configured)return;const s=getSupabase();if(!s)return;setSaving(i);if(item.id){await s.from("announcements").update({title:item.title,body:item.body,badge:item.badge||null,priority:item.priority,active:item.active,published_at:item.published_at??new Date().toISOString()}).eq("id",item.id);}else{const {data}=await s.from("announcements").insert({title:item.title,body:item.body,badge:item.badge||null,priority:item.priority,active:item.active,published_at:new Date().toISOString()}).select("*").single();if(data)patch(i,data as Announcement);}setSaving(null);}
  async function remove(item:Announcement,i:number){if(configured&&item.id)await getSupabase()?.from("announcements").delete().eq("id",item.id);setItems(r=>r.filter((_,n)=>n!==i));}
  if(accessLoading)return <div className="glass rounded-[30px] p-10 text-center text-zinc-600">جارٍ التحقق من الصلاحية...</div>; if(!authorized)return <div className="glass rounded-[30px] p-10 text-center"><h1 className="text-2xl font-black">غير مصرح لك</h1></div>;
  return <div className="mx-auto max-w-[1200px] space-y-5"><header className="glass rounded-[32px] p-7 sm:p-9"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[16px] border border-[rgba(213,166,116,.16)] bg-[rgba(213,166,116,.05)]"><BellRing size={20} className="bronze-text"/></span><div><p className="text-[10px] font-black text-zinc-700">إدارة الإعلانات</p><h1 className="mt-1 text-3xl font-black">إدارة الإعلانات</h1></div></div><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-600">انشر تنبيهًا أو تعميمًا يظهر في صفحة الإعلانات العامة. الأولوية الأعلى تظهر أولًا.</p></header>
    {!configured&&<div className="rounded-[20px] border border-[rgba(213,166,116,.15)] bg-[rgba(213,166,116,.04)] px-5 py-4 text-sm text-zinc-600">وضع معاينة: الحفظ الدائم يتفعل بعد ربط قاعدة البيانات.</div>}
    <div className="space-y-4">{items.map((item,i)=><article key={item.id??i} className="glass rounded-[28px] p-5 sm:p-6"><div className="grid gap-4 lg:grid-cols-[1fr_170px_120px]"><label><span className="mb-2 block text-[10px] font-black text-zinc-700">عنوان الإعلان</span><input value={item.title} onChange={e=>patch(i,{title:e.target.value})} className="w-full rounded-[17px] border border-white/[.07] bg-black/25 px-4 py-3 outline-none"/></label><label><span className="mb-2 block text-[10px] font-black text-zinc-700">الشارة</span><input value={item.badge??""} onChange={e=>patch(i,{badge:e.target.value})} className="w-full rounded-[17px] border border-white/[.07] bg-black/25 px-4 py-3 outline-none"/></label><label><span className="mb-2 block text-[10px] font-black text-zinc-700">الأولوية</span><input type="number" value={item.priority} onChange={e=>patch(i,{priority:Number(e.target.value)})} className="w-full rounded-[17px] border border-white/[.07] bg-black/25 px-4 py-3 outline-none"/></label></div><label className="mt-4 block"><span className="mb-2 block text-[10px] font-black text-zinc-700">النص</span><textarea rows={4} value={item.body} onChange={e=>patch(i,{body:e.target.value})} className="w-full resize-y rounded-[18px] border border-white/[.07] bg-black/25 px-4 py-3 leading-7 outline-none"/></label><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/[.055] pt-5"><label className="flex items-center gap-2 text-xs font-black text-zinc-600"><input type="checkbox" checked={item.active} onChange={e=>patch(i,{active:e.target.checked})}/><Radio size={13} className={item.active?"text-[#7f9b8c]":"text-zinc-700"}/> منشور</label><div className="flex gap-2"><button onClick={()=>remove(item,i)} className="inline-flex items-center gap-2 rounded-[15px] border border-[rgba(183,106,91,.15)] px-4 py-2.5 text-xs font-black text-[#c87a6b]"><Trash2 size={14}/> حذف</button><button onClick={()=>save(item,i)} disabled={!configured||saving===i} className="inline-flex items-center gap-2 rounded-[15px] bg-[#d5a674] px-4 py-2.5 text-xs font-black text-[#17110d] disabled:opacity-40"><Save size={14}/> حفظ ونشر</button></div></div></article>)}</div>
    <button onClick={add} className="flex w-full items-center justify-center gap-2 rounded-[22px] border border-dashed border-[rgba(213,166,116,.22)] bg-[rgba(213,166,116,.025)] px-5 py-5 text-sm font-black bronze-text"><Plus size={18}/> إعلان جديد</button>
  </div>;
}
