"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from "lucide-react";
import { can } from "@/lib/auth";
import { useCurrentProfile } from "@/lib/use-current-profile";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase/client";

type Q={id:string;question:string;required:boolean;active:boolean;position:number};
const DEMO:Q[]=[{id:"q1",question:"ليش تبي تنضم لكلية الضباط الأمنية؟",required:true,active:true,position:1},{id:"q2",question:"وش المهارات القيادية اللي تشوف أنها تميزك؟ اذكر مثال.",required:true,active:true,position:2},{id:"q3",question:"كيف تتصرف لو استلمت مسؤولية فريق وحدث خلاف بين أفراده أثناء المهمة؟",required:true,active:true,position:3},{id:"q4",question:"وش يعني لك الانضباط العسكري؟ وكيف تثبته عمليًا؟",required:true,active:true,position:4},{id:"q5",question:"اذكر هدفك بعد التخرج من كلية الضباط الأمنية.",required:true,active:true,position:5}];
export default function QuestionsPage(){const configured=isSupabaseConfigured();const {profile,loading:accessLoading}=useCurrentProfile();const allowed=Boolean(profile&&(profile.is_owner||can(profile,"manage_application_questions")));const [rows,setRows]=useState<Q[]>(configured?[]:DEMO);const [saving,setSaving]=useState(false);
 async function load(){const s=getSupabase();if(!s)return;const {data}=await s.from("application_questions").select("*").eq("target_key","officer-college").order("position");setRows((data??[]) as Q[])} useEffect(()=>{if(configured)load()},[configured]);
 const add=()=>setRows(v=>[...v,{id:`new-${Date.now()}`,question:"سؤال جديد",required:true,active:true,position:v.length+1}]);
 const patch=(id:string,p:Partial<Q>)=>setRows(v=>v.map(q=>q.id===id?{...q,...p}:q));
 const move=(i:number,d:number)=>setRows(v=>{const n=[...v];const j=i+d;if(j<0||j>=n.length)return v;[n[i],n[j]]=[n[j],n[i]];return n.map((q,k)=>({...q,position:k+1}))});
 const remove=async(q:Q)=>{setRows(v=>v.filter(x=>x.id!==q.id));if(configured&&!q.id.startsWith("new-"))await getSupabase()?.from("application_questions").delete().eq("id",q.id)};
 async function save(){if(!configured)return;const s=getSupabase();if(!s)return;setSaving(true);for(const [i,q] of rows.entries()){const payload={target_key:"officer-college",question:q.question.trim(),required:q.required,active:q.active,position:i+1};if(q.id.startsWith("new-"))await s.from("application_questions").insert(payload);else await s.from("application_questions").update(payload).eq("id",q.id)}await load();setSaving(false)}
 if(accessLoading)return <div className="glass rounded-[28px] p-10 text-center text-zinc-600">جارٍ التحقق...</div>;if(!allowed)return <div className="glass rounded-[28px] p-10 text-center">غير مصرح لك.</div>;
 return <div className="mx-auto max-w-5xl space-y-4"><header className="glass rounded-[28px] p-5 sm:p-7"><p className="section-kicker">إدارة أسئلة كلية الضباط</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black md:text-5xl">أسئلة كلية الضباط</h1><p className="mt-2 text-sm text-zinc-600">أضيفي، عدلي، احذفي ورتبي الأسئلة. التغيير يظهر مباشرة في صفحة التقديم بعد الحفظ.</p></div><button onClick={add} className="inline-flex items-center justify-center gap-2 rounded-[15px] border border-[rgba(213,166,116,.16)] bg-[rgba(213,166,116,.05)] px-4 py-3 text-xs font-black bronze-text"><Plus size={15}/> إضافة سؤال</button></div></header>
 {!configured&&<div className="rounded-[18px] border border-[rgba(213,166,116,.15)] bg-[rgba(213,166,116,.05)] p-4 text-xs text-zinc-500">وضع المعاينة: التعديل يعمل بصريًا فقط ولا يُحفظ بعد تحديث الصفحة.</div>}
 <section className="space-y-2">{rows.map((q,i)=><article key={q.id} className="glass grid gap-3 rounded-[22px] p-4 md:grid-cols-[52px_1fr_auto] md:items-center"><div className="flex flex-row gap-1 md:flex-col"><button onClick={()=>move(i,-1)} className="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[.06] text-zinc-700"><ArrowUp size={13}/></button><button onClick={()=>move(i,1)} className="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[.06] text-zinc-700"><ArrowDown size={13}/></button></div><div><p className="mb-2 text-[9px] font-black text-zinc-700">سؤال {String(i+1).padStart(2,"0")}</p><textarea rows={2} value={q.question} onChange={e=>patch(q.id,{question:e.target.value})} className="ds-input resize-none"/></div><div className="flex items-center gap-2 md:flex-col md:items-stretch"><button onClick={()=>patch(q.id,{required:!q.required})} className={`rounded-[12px] border px-3 py-2 text-[10px] font-black ${q.required?"border-[rgba(127,155,140,.18)] bg-[rgba(127,155,140,.06)] text-[#91ad9d]":"border-white/[.06] text-zinc-700"}`}>{q.required?"إجباري":"اختياري"}</button><button onClick={()=>patch(q.id,{active:!q.active})} className={`rounded-[12px] border px-3 py-2 text-[10px] font-black ${q.active?"border-[rgba(213,166,116,.15)] text-[#d5a674]":"border-white/[.06] text-zinc-700"}`}>{q.active?"ظاهر":"مخفي"}</button><button onClick={()=>remove(q)} className="flex items-center justify-center rounded-[12px] border border-[rgba(183,106,91,.14)] px-3 py-2 text-[#b96f62]"><Trash2 size={14}/></button></div></article>)}</section>
 <button onClick={save} disabled={!configured||saving} className="flex w-full items-center justify-center gap-2 rounded-[17px] bg-[#d5a674] px-5 py-4 font-black text-black disabled:opacity-35"><Save size={16}/>{saving?"جارٍ الحفظ...":"حفظ ونشر الأسئلة"}</button></div>}
