"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Filter, GraduationCap, RefreshCcw, Save, Search, XCircle } from "lucide-react";
import { can } from "@/lib/auth";
import { useCurrentProfile } from "@/lib/use-current-profile";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase/client";
import { useOrganization } from "@/lib/use-organization";

type Status="new"|"reviewing"|"accepted"|"rejected";
type Answer={question_id:string;question:string;answer:string};
type Row={id:string;target_key:string;target_name:string;full_name:string;game_name:string;discord_name:string;job_code:string;copy_id:string;military_rank:string;motivation:string;experience:string;availability:string;answers:Answer[];status:Status;reviewer_note:string|null;assigned_title:string|null;created_at?:string};
const DEMO:Row[]=[
{id:"a1",target_key:"admin-affairs",target_name:"الشؤون الإدارية",full_name:"متقدم تجريبي",game_name:"Example",discord_name:"example",job_code:"F-300",copy_id:"104",military_rank:"رقيب",motivation:"أحب التنظيم والرصد.",experience:"تقارير وحضور.",availability:"مساءً",answers:[],status:"new",reviewer_note:"",assigned_title:""},
{id:"a2",target_key:"officer-college",target_name:"كلية الضباط الأمنية",full_name:"متقدم للكلية",game_name:"متقدم تجريبي",discord_name:"cadet",job_code:"F-220",copy_id:"220",military_rank:"رقيب أول",motivation:"أطمح للمسار القيادي.",experience:"قيادة فرق صغيرة.",availability:"يوميًا",answers:[{question_id:"q1",question:"ليش تبي تنضم لكلية الضباط الأمنية؟",answer:"لأني أبي أتطور بالمسار القيادي وأتحمل مسؤولية أكبر."}],status:"reviewing",reviewer_note:"الإجابات جيدة مبدئيًا",assigned_title:"طالب كلية الضباط الأمنية"}
];
const statusLabel:{[K in Status]:string}={new:"جديد",reviewing:"تحت المراجعة",accepted:"مقبول",rejected:"مرفوض"};

export default function ApplicationsDashboard(){
 const configured=isSupabaseConfigured(); const {profile,loading:accessLoading}=useCurrentProfile();
 const {units,titles,loading:orgLoading}=useOrganization();
 const authorized=Boolean(profile&&(profile.is_owner||can(profile,"manage_applications")));
 const [rows,setRows]=useState<Row[]>(configured?[]:DEMO); const [target,setTarget]=useState("all"); const [status,setStatus]=useState<"all"|Status>("all"); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(configured); const [saving,setSaving]=useState<string|null>(null); const [notice,setNotice]=useState("");
 async function load(){const s=getSupabase();if(!s)return;setLoading(true);const {data,error}=await s.from("department_applications").select("*").order("created_at",{ascending:false});if(!error)setRows((data??[]) as Row[]);setLoading(false)}
 useEffect(()=>{if(configured)load()},[configured]);
 const targetOptions=useMemo(()=>[...units.filter(u=>u.application_enabled&&u.active).sort((a,b)=>a.sort_order-b.sort_order).map(u=>({key:u.key,name:u.name})),{key:"officer-college",name:"كلية الضباط الأمنية"}],[units]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>(target==="all"||r.target_key===target)&&(status==="all"||r.status===status)&&(!q||[r.full_name,r.game_name,r.discord_name,r.job_code,r.copy_id,r.military_rank,r.target_name].some(v=>v?.toLowerCase().includes(q))))},[rows,target,status,search]);
 const patch=(id:string,p:Partial<Row>)=>setRows(v=>v.map(r=>r.id===id?{...r,...p}:r));
 async function save(row:Row){if(!configured){setNotice("وضع المعاينة: القرار غير محفوظ بعد تحديث الصفحة.");return}const s=getSupabase();if(!s)return;setSaving(row.id);const {error}=await s.from("department_applications").update({status:row.status,reviewer_note:row.reviewer_note||null,assigned_title:row.assigned_title||null,reviewed_by:profile?.id??null,reviewed_at:new Date().toISOString()}).eq("id",row.id);setSaving(null);setNotice(error?`تعذر الحفظ: ${error.message}`:"تم حفظ قرار الطلب.")}
 if(accessLoading||orgLoading)return <div className="glass rounded-[28px] p-10 text-center text-zinc-600">جارٍ التحقق...</div>;
 if(!authorized)return <div className="glass rounded-[28px] p-10 text-center"><h1 className="text-2xl font-black">غير مصرح لك</h1><p className="mt-2 text-zinc-600">تحتاج صلاحية مراجعة طلبات الأقسام.</p></div>;
 return <div className="mx-auto max-w-[1500px] space-y-4"><header className="glass rounded-[28px] p-5 sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">التقديم الموحّد</p><h1 className="mt-2 text-3xl font-black md:text-5xl">طلبات جميع الأقسام</h1><p className="mt-2 text-sm text-zinc-600">الأسماء والمسميات هنا مرتبطة بالهيكل التنظيمي. إذا تغير قسم أو مسمى، يتحدث التسكين تلقائيًا.</p></div><button onClick={load} disabled={!configured} className="inline-flex items-center justify-center gap-2 rounded-[15px] border border-white/[.07] px-4 py-3 text-xs font-black text-zinc-600 disabled:opacity-30"><RefreshCcw size={15}/> تحديث</button></div></header>
 <section className="glass grid gap-2 rounded-[22px] p-3 md:grid-cols-[1fr_240px_190px_auto]"><div className="relative"><Search size={15} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-zinc-700"/><input className="ds-input py-3 pr-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم، الكود، الرتبة..."/></div><select className="ds-input py-3" value={target} onChange={e=>setTarget(e.target.value)}><option value="all">كل الجهات</option>{targetOptions.map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select><select className="ds-input py-3" value={status} onChange={e=>setStatus(e.target.value as any)}><option value="all">كل الحالات</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="inline-flex items-center justify-center gap-2 rounded-[15px] border border-white/[.06] bg-black/20 px-4 text-xs font-black text-zinc-700"><Filter size={14}/>{filtered.length}</div></section>
 {!configured&&<div className="rounded-[18px] border border-[rgba(213,166,116,.15)] bg-[rgba(213,166,116,.05)] p-4 text-xs text-zinc-500">وضع المعاينة — الطلبات المعروضة أمثلة.</div>}{notice&&<div className="rounded-[18px] border border-[rgba(127,155,140,.16)] bg-[rgba(127,155,140,.04)] p-4 text-xs text-zinc-500">{notice}</div>}
 <div className="space-y-3">{loading?<div className="h-72 animate-pulse rounded-[28px] bg-white/[.02]"/>:filtered.map(row=>{const availableTitles=row.target_key==="officer-college"?["طالب كلية الضباط الأمنية"]:titles.filter(t=>t.unit_key===row.target_key&&t.active&&t.application_assignable).sort((a,b)=>a.sort_order-b.sort_order).map(t=>t.name);return <article key={row.id} className="glass overflow-hidden rounded-[26px]"><div className="flex flex-col gap-3 border-b border-white/[.055] p-5 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-lg font-black text-zinc-200">{row.full_name}</h2>{row.target_key==="officer-college"&&<GraduationCap size={16} className="bronze-text"/>}</div><p className="mt-1 text-xs text-zinc-600">{row.target_name} • {row.military_rank} • {row.job_code} • كوبي آي دي {row.copy_id}</p><p className="mt-1 text-[10px] text-zinc-700">{row.game_name} • الديسكورد: {row.discord_name}</p></div><StatusPill status={row.status}/></div>
 <div className="grid gap-3 p-5 lg:grid-cols-3"><Info title="سبب التقديم" text={row.motivation}/><Info title="الخبرات" text={row.experience}/><Info title="التواجد" text={row.availability}/></div>
 {row.answers?.length>0&&<div className="border-t border-white/[.055] px-5 py-4"><p className="mb-3 text-[10px] font-black bronze-text">إجابات أسئلة القبول</p><div className="grid gap-2 lg:grid-cols-2">{row.answers.map((a,i)=><div key={a.question_id||i} className="rounded-[16px] border border-white/[.055] bg-black/15 p-4"><p className="text-[10px] font-black text-zinc-700">{a.question}</p><p className="mt-2 text-sm leading-6 text-zinc-400">{a.answer}</p></div>)}</div></div>}
 <div className="grid gap-3 border-t border-white/[.055] bg-black/10 p-5 xl:grid-cols-[190px_1fr_280px_auto] xl:items-end"><label><span className="mb-2 block text-[10px] font-black text-zinc-700">الحالة</span><select className="ds-input py-3" value={row.status} onChange={e=>patch(row.id,{status:e.target.value as Status})}>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span className="mb-2 block text-[10px] font-black text-zinc-700">ملاحظة المراجع</span><input className="ds-input py-3" value={row.reviewer_note??""} onChange={e=>patch(row.id,{reviewer_note:e.target.value})}/></label><label><span className="mb-2 block text-[10px] font-black text-zinc-700">المسمى عند القبول</span><select className="ds-input py-3" value={row.assigned_title??""} onChange={e=>patch(row.id,{assigned_title:e.target.value})}><option value="">بدون تحديد</option>{availableTitles.map(t=><option key={t}>{t}</option>)}</select></label><button onClick={()=>save(row)} disabled={saving===row.id} className="inline-flex h-[46px] items-center justify-center gap-2 rounded-[15px] bg-[#d5a674] px-5 text-sm font-black text-black disabled:opacity-35"><Save size={15}/>{saving===row.id?"حفظ...":"حفظ القرار"}</button></div>
 </article>})}</div></div>;
}
function StatusPill({status}:{status:Status}){const data={new:[Clock3,"جديد","text-[#d5a674]"],reviewing:[Filter,"تحت المراجعة","text-[#91a7b7]"],accepted:[CheckCircle2,"مقبول","text-[#91ad9d]"],rejected:[XCircle,"مرفوض","text-[#c87a6b]"]} as const;const [Icon,label,color]=data[status];return <span className={`inline-flex w-fit items-center gap-2 rounded-full border border-white/[.07] bg-black/20 px-3 py-2 text-[10px] font-black ${color}`}><Icon size={13}/>{label}</span>}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-[16px] border border-white/[.055] bg-white/[.012] p-4"><p className="text-[9px] font-black text-zinc-700">{title}</p><p className="mt-2 text-sm leading-6 text-zinc-400">{text||"—"}</p></div>}
