"use client";

import Link from "next/link";
import { ArrowLeft, BadgeCheck, Building2, GraduationCap, Layers3, Send } from "lucide-react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { DepartmentIcon, DEPARTMENT_TONES } from "@/components/department-visual";
import { useOrganization } from "@/lib/use-organization";

export default function ApplyHubPage(){
  const {units,titles,loading}=useOrganization();
  const targets=units.filter(u=>u.key!=="military-police"&&u.application_enabled&&u.active).sort((a,b)=>a.sort_order-b.sort_order);
  return <main className="min-h-screen overflow-hidden"><Navbar/><div className="soft-grid pointer-events-none fixed inset-x-0 top-0 h-[420px] opacity-30"/>
    <div className="relative mx-auto max-w-[1540px] px-4 pb-14 pt-28 sm:px-6 md:pt-32 lg:px-8">
      <header className="glass-strong overflow-hidden rounded-[32px] p-5 sm:p-7"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="section-kicker">مركز التقديم</p><h1 className="display-title mt-2 text-4xl font-black md:text-6xl">مركز التقديم <span className="bronze-text">الموحّد</span></h1><p className="mt-3 max-w-3xl text-sm leading-7 text-zinc-500">اختر الجهة فقط. اسم القسم ومسمياته تتحدث تلقائيًا من الهيكل، لذلك المتقدم دائمًا يشوف النسخة الحالية المعتمدة.</p></div><div className="grid grid-cols-3 gap-2">{[[targets.length+1,"جهة"],["01","نموذج"],["التقديم متاح","مراجعة"]].map(([v,l])=><div key={String(l)} className="rounded-[18px] border border-white/[.06] bg-black/20 p-3 text-center"><p className="text-lg font-black bronze-text">{v}</p><p className="text-[9px] font-black text-zinc-700">{l}</p></div>)}</div></div></header>

      {loading?<div className="mt-4 h-72 animate-pulse rounded-[28px] bg-white/[.02]"/>:<section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {targets.map(target=>{const tone=DEPARTMENT_TONES[target.accent];const count=titles.filter(t=>t.unit_key===target.key&&t.active&&t.application_assignable).length;return <Link key={target.key} href={`/apply/${target.key}`} className={`group relative overflow-hidden rounded-[26px] border p-5 transition hover:-translate-y-1 ${tone.border} bg-white/[.018]`}><div className={`pointer-events-none absolute inset-0 bg-gradient-to-bl ${tone.soft} via-transparent to-transparent opacity-40`}/><div className="relative"><div className="flex items-start justify-between"><span className={`flex h-11 w-11 items-center justify-center rounded-[15px] border ${tone.border} ${tone.bg} ${tone.text}`}><DepartmentIcon iconKey={target.icon_key} size={20}/></span><span className="rounded-full border border-white/[.06] px-2.5 py-1 text-[9px] font-black text-zinc-700">التقديم مفتوح</span></div><h2 className="mt-5 text-lg font-black text-zinc-200">{target.name}</h2><p className="mt-2 min-h-[44px] text-xs leading-6 text-zinc-600">{target.description}</p><div className="mt-4 flex items-center justify-between border-t border-white/[.055] pt-4"><span className="inline-flex items-center gap-2 text-[10px] font-black text-zinc-700"><BadgeCheck size={13}/>{count} مسميات للتسكين</span><span className={`inline-flex items-center gap-2 text-xs font-black ${tone.text}`}>ابدأ الطلب <ArrowLeft size={14}/></span></div></div></Link>})}
        <Link href="/apply/officer-college" className="group relative overflow-hidden rounded-[26px] border border-[rgba(213,166,116,.24)] bg-[linear-gradient(145deg,rgba(213,166,116,.10),rgba(18,18,17,.86))] p-5 transition hover:-translate-y-1"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-[15px] border border-[rgba(213,166,116,.18)] bg-[rgba(213,166,116,.06)]"><GraduationCap size={20} className="bronze-text"/></span><span className="rounded-full border border-[rgba(213,166,116,.14)] px-2.5 py-1 text-[9px] font-black bronze-text">اختبار خاص</span></div><h2 className="mt-5 text-lg font-black">كلية الضباط الأمنية</h2><p className="mt-2 min-h-[44px] text-xs leading-6 text-zinc-600">مسار مستقل بأسئلة قبول قابلة للتعديل من مركز القيادة.</p><div className="mt-4 flex items-center justify-between border-t border-white/[.055] pt-4"><span className="inline-flex items-center gap-2 text-[10px] font-black text-zinc-700"><BadgeCheck size={13}/>أسئلة ديناميكية</span><span className="inline-flex items-center gap-2 text-xs font-black bronze-text">ابدأ الاختبار <ArrowLeft size={14}/></span></div></Link>
      </section>}

      <section className="mt-4 grid gap-3 lg:grid-cols-[1.2fr_.8fr]"><div className="glass rounded-[24px] p-5"><div className="flex items-center gap-3"><Layers3 size={18} className="bronze-text"/><div><p className="text-sm font-black text-zinc-300">المتقدم ما يحتاج يعرف النظام الداخلي</p><p className="mt-1 text-xs text-zinc-600">يختار الجهة، يعبّي النموذج، ويستلم المسؤول الطلب في لوحة المراجعة.</p></div></div></div><div className="glass rounded-[24px] p-5"><div className="flex items-center gap-3"><Send size={18} className="bronze-text"/><div><p className="text-sm font-black text-zinc-300">الأقسام تتحدث تلقائيًا</p><p className="mt-1 text-xs text-zinc-600">إذا غيرت اسم قسم من لوحة الهيكل يظهر هنا مباشرة.</p></div></div></div></section>
    </div><Footer/></main>;
}
