"use client";

import { useState } from "react";
import { Bell, Database, KeyRound, Save, Settings2, ShieldCheck } from "lucide-react";
import { can } from "@/lib/auth";
import { isSupabaseConfigured } from "@/lib/supabase/client";
import { useCurrentProfile } from "@/lib/use-current-profile";

export default function SettingsPage(){
  const {profile,loading}=useCurrentProfile(); const allowed=Boolean(profile&&(profile.is_owner||can(profile,"manage_settings"))); const [saved,setSaved]=useState(false); const [flags,setFlags]=useState({showStatus:true,publicAnnouncements:true,requireReview:true,showStructure:true});
  if(loading)return <div className="glass rounded-[30px] p-10 text-center text-zinc-600">جارٍ التحقق من الصلاحية...</div>; if(!allowed)return <div className="glass rounded-[30px] p-10 text-center"><h1 className="text-2xl font-black">غير مصرح لك</h1></div>;
  const rows=[ ["showStatus","إظهار حالة البوابة","يظهر مؤشر الحالة في الواجهة العامة",ShieldCheck], ["publicAnnouncements","إظهار الإعلانات للعامة","صفحة الإعلانات تكون متاحة بدون تسجيل",Bell], ["requireReview","تفعيل مراجعة المحتوى","المحرر يرسل مسودة قبل النشر",KeyRound], ["showStructure","إظهار الهيكل التنظيمي","عرض صفحة الهيكل في التنقل العام",Settings2] ] as const;
  return <div className="mx-auto max-w-[1100px] space-y-5"><header className="glass rounded-[32px] p-7 sm:p-9"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[16px] border border-[rgba(213,166,116,.16)] bg-[rgba(213,166,116,.05)]"><Settings2 size={20} className="bronze-text"/></span><div><p className="text-[10px] font-black text-zinc-700">إعدادات البوابة</p><h1 className="mt-1 text-3xl font-black">إعدادات البوابة</h1></div></div></header>
    <section className="grid gap-4 md:grid-cols-3"><div className="glass rounded-[24px] p-5"><Database size={18} className={isSupabaseConfigured()?"text-[#7f9b8c]":"text-[#d5a674]"}/><p className="mt-4 text-sm font-black">قاعدة البيانات</p><p className="mt-1 text-xs text-zinc-700">{isSupabaseConfigured()?"متصلة":"وضع معاينة محلي"}</p></div><div className="glass rounded-[24px] p-5"><ShieldCheck size={18} className="text-[#7f9b8c]"/><p className="mt-4 text-sm font-black">الحماية</p><p className="mt-1 text-xs text-zinc-700">حماية الصفوف + صلاحيات مركبة</p></div><div className="glass rounded-[24px] p-5"><KeyRound size={18} className="bronze-text"/><p className="mt-4 text-sm font-black">مالك النظام</p><p className="mt-1 text-xs text-zinc-700">صلاحية شاملة</p></div></section>
    <section className="glass rounded-[30px] p-5 sm:p-6"><div className="mb-5"><p className="font-black">خصائص البوابة</p><p className="mt-1 text-xs text-zinc-700">هذه الإعدادات قابلة للربط بقاعدة البيانات عند تشغيل البوابة بشكل نهائي.</p></div><div className="divide-y divide-white/[.055]">{rows.map(([key,title,desc,Icon])=><label key={key} className="flex cursor-pointer items-center gap-4 py-5"><span className="flex h-10 w-10 items-center justify-center rounded-[14px] border border-white/[.07] bg-black/20"><Icon size={17} className="text-zinc-600"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-black text-zinc-300">{title}</span><span className="mt-1 block text-xs text-zinc-700">{desc}</span></span><input type="checkbox" checked={flags[key]} onChange={e=>setFlags(v=>({...v,[key]:e.target.checked}))} className="h-4 w-4"/></label>)}</div><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1700)}} className="mt-5 inline-flex items-center gap-2 rounded-[15px] bg-[#d5a674] px-5 py-3 text-xs font-black text-[#17110d]"><Save size={14}/>{saved?"تم الحفظ للمعاينة":"حفظ الإعدادات"}</button></section>
  </div>;
}
