"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ClipboardCheck, RotateCcw, XCircle } from "lucide-react";
import { can } from "@/lib/auth";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase/client";
import { useCurrentProfile } from "@/lib/use-current-profile";

type Draft = { id: string; slug: string; change_kind: "upsert"|"delete"; payload: Record<string, unknown>; status: string; created_at?: string; creator_name?: string | null };
const DEMO: Draft[] = [{ id:"preview-draft", slug:"laws", change_kind:"upsert", payload:{category:"الانضباط",title:"مثال — تعديل بانتظار الاعتماد",body:"هذه مسودة توضيحية لا تظهر في الصفحة العامة حتى يتم اعتمادها ونشرها."}, status:"pending_review", creator_name:"عضو تجريبي", created_at:new Date().toISOString() }];

const slugName: Record<string,string> = { laws:"القوانين",protocols:"البروتوكولات",promotions:"شروط الترقيات",leaves:"شروط الإجازات" };

export default function ReviewPage(){
  const {profile,loading:accessLoading}=useCurrentProfile(); const allowed=Boolean(profile&&(profile.is_owner||can(profile,"publish_content"))); const configured=isSupabaseConfigured(); const [rows,setRows]=useState<Draft[]>(configured?[]:DEMO); const [busy,setBusy]=useState<string|null>(null);
  async function load(){const s=getSupabase();if(!s)return;const {data}=await s.from("content_drafts").select("*").eq("status","pending_review").order("created_at",{ascending:false});setRows((data??[]) as Draft[]);} useEffect(()=>{load();},[]);
  async function approve(id:string){setBusy(id);const s=getSupabase();if(!s){setRows(r=>r.filter(x=>x.id!==id));setBusy(null);return;}await s.rpc("publish_content_draft",{draft_id:id});await load();setBusy(null);}
  async function reject(id:string){setBusy(id);const s=getSupabase();if(!s){setRows(r=>r.filter(x=>x.id!==id));setBusy(null);return;}await s.from("content_drafts").update({status:"rejected",reviewed_at:new Date().toISOString()}).eq("id",id);await load();setBusy(null);}
  if(accessLoading)return <div className="glass rounded-[30px] p-10 text-center text-zinc-600">جارٍ التحقق من الصلاحية...</div>; if(!allowed)return <div className="glass rounded-[30px] p-10 text-center"><h1 className="text-2xl font-black">غير مصرح لك</h1><p className="mt-2 text-zinc-600">طابور المراجعة يتطلب صلاحية اعتماد ونشر.</p></div>;
  return <div className="mx-auto max-w-[1200px] space-y-5"><header className="glass rounded-[32px] p-7 sm:p-9"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[16px] border border-[rgba(213,166,116,.16)] bg-[rgba(213,166,116,.05)]"><ClipboardCheck size={20} className="bronze-text"/></span><div><p className="text-[10px] font-black text-zinc-700">طابور المراجعة</p><h1 className="mt-1 text-3xl font-black">طابور المراجعة</h1></div></div><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-600">المسودات التي أرسلها المحررون لا تظهر للعامة حتى تراجعها الجهة المخولة بالنشر.</p></header>
    <div className="flex items-center justify-between rounded-[22px] border border-white/[.06] bg-white/[.015] px-5 py-4"><span className="text-sm font-black text-zinc-500">بانتظار القرار: <b className="bronze-text">{rows.length}</b></span><button onClick={load} className="inline-flex items-center gap-2 text-xs font-black text-zinc-700 hover:text-zinc-400"><RotateCcw size={14}/> تحديث</button></div>
    <section className="space-y-4">{rows.length?rows.map((row)=><article key={row.id} className="glass rounded-[28px] p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full border border-[rgba(213,166,116,.16)] bg-[rgba(213,166,116,.05)] px-2.5 py-1 text-[10px] font-black bronze-text">{slugName[row.slug]??row.slug}</span><span className="rounded-full border border-white/[.07] px-2.5 py-1 text-[10px] font-black text-zinc-600">{row.change_kind==="delete"?"طلب حذف":"تعديل/إضافة"}</span></div><h2 className="mt-4 text-xl font-black text-zinc-200">{String(row.payload.title??"بدون عنوان")}</h2><p className="mt-2 text-xs font-black text-zinc-700">{String(row.payload.category??"")} • بواسطة {row.creator_name??"محرر"}</p><p className="mt-4 max-w-3xl whitespace-pre-line text-sm leading-7 text-zinc-500">{String(row.payload.body??"")}</p></div><div className="flex shrink-0 gap-2"><button onClick={()=>reject(row.id)} disabled={busy===row.id} className="inline-flex items-center gap-2 rounded-[15px] border border-[rgba(183,106,91,.16)] px-4 py-2.5 text-xs font-black text-[#c87a6b]"><XCircle size={14}/> رفض</button><button onClick={()=>approve(row.id)} disabled={busy===row.id} className="inline-flex items-center gap-2 rounded-[15px] bg-[#7f9b8c] px-4 py-2.5 text-xs font-black text-[#0d1511]"><CheckCircle2 size={14}/> اعتماد ونشر</button></div></div></article>):<div className="glass rounded-[28px] p-12 text-center"><CheckCircle2 size={28} className="mx-auto text-[#7f9b8c]"/><p className="mt-4 font-black text-zinc-400">لا توجد مسودات معلقة</p></div>}</section>
  </div>;
}
