"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Loader2, Search, ShieldAlert, XCircle } from "lucide-react";
import { can } from "@/lib/auth";
import { useCurrentProfile } from "@/lib/use-current-profile";
import { getSupabase, isSupabaseConfigured } from "@/lib/supabase/client";
import { DEMO_ROSTER, getResolvedRank, type PublicRosterEntry } from "@/lib/roster";

type Violation={id:string;roster_id:string|null;person_name:string;copy_id:string;job_code:string|null;reason:string;value:string;action:string;executed:boolean;evidence:string|null;recorded_by_name:string;recorded_by_title:string;created_at:string};
const DEMO:Violation[]=[{id:"v1",roster_id:"r3",person_name:"مثال عسكري",copy_id:"220",job_code:"F-312",reason:"مثال توضيحي لمخالفة داخلية",value:"تنبيه",action:"تنبيه شفهي",executed:false,evidence:null,recorded_by_name:"رئيس النظام — وضع المعاينة",recorded_by_title:"مالك النظام",created_at:new Date().toISOString()}];

export default function MilitaryPolicePage(){
 const configured=isSupabaseConfigured(); const {profile,loading:profileLoading}=useCurrentProfile();
 const allowed=Boolean(profile&&(profile.is_owner||can(profile,"manage_military_police")||profile.department_key==="military-police"));
 const [rows,setRows]=useState<PublicRosterEntry[]>(configured?[]:DEMO_ROSTER.filter(r=>r.member_type==="sector_member")); const [violations,setViolations]=useState<Violation[]>(configured?[]:DEMO); const [search,setSearch]=useState(""); const [rosterId,setRosterId]=useState(""); const [reason,setReason]=useState(""); const [value,setValue]=useState(""); const [action,setAction]=useState(""); const [executed,setExecuted]=useState(false); const [evidence,setEvidence]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 async function load(){const s=getSupabase();if(!s)return;const [r,v]=await Promise.all([s.from("personnel_roster").select("*").eq("active",true).eq("member_type","sector_member").order("name"),s.from("military_police_violations").select("*").order("created_at",{ascending:false}).limit(100)]);if(!r.error)setRows((r.data||[]) as PublicRosterEntry[]);if(!v.error)setViolations((v.data||[]) as Violation[])}
 useEffect(()=>{if(configured&&allowed)load()},[configured,allowed]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return rows.filter(r=>!q||[r.name,r.copy_id,r.job_code,getResolvedRank(r)].some(v=>String(v||"").toLowerCase().includes(q)))},[rows,search]); const person=rows.find(r=>r.id===rosterId);
 async function save(){if(!person||!profile||!reason.trim()||!action.trim())return;setSaving(true);setMessage("");const payload={roster_id:person.id,person_name:person.name,copy_id:person.copy_id||"—",job_code:person.job_code,reason:reason.trim(),value:value.trim()||"بدون قيمة",action:action.trim(),executed,evidence:evidence.trim()||null,recorded_by:profile.id,recorded_by_name:profile.name,recorded_by_title:profile.title||"بدون مسمى"};const s=getSupabase();if(!s){setViolations(v=>[{id:`demo-${Date.now()}`,...payload,created_at:new Date().toISOString()} as Violation,...v]);setMessage("تم التسجيل في وضع المعاينة.");setSaving(false);return}const {error}=await s.from("military_police_violations").insert(payload);if(error)setMessage(error.message);else{setMessage("تم تسجيل المخالفة.");setReason("");setValue("");setAction("");setExecuted(false);setEvidence("");await load()}setSaving(false)}
 if(profileLoading)return <div className="p-10 text-zinc-600">جارٍ التحقق...</div>; if(!allowed)return <div className="rounded-[28px] border border-white/[.07] p-10 text-center"><ShieldAlert className="mx-auto text-zinc-700"/><h1 className="mt-4 text-2xl font-black">واجهة الشرطة العسكرية</h1><p className="mt-2 text-sm text-zinc-600">الانضمام للشرطة العسكرية بالترشيح فقط، وهذه الواجهة تظهر لأصحاب الصلاحية.</p></div>;
 return <div className="mx-auto max-w-[1400px] space-y-5"><header className="rounded-[32px] border border-[#8c3b32]/20 bg-[linear-gradient(135deg,rgba(60,25,22,.22),rgba(10,10,10,.92))] p-6 sm:p-8"><p className="text-[10px] font-black text-[#b96f62]">الشرطة العسكرية</p><h1 className="mt-3 text-4xl font-black">سجل المخالفات العسكرية</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-zinc-600">لا يوجد تقديم مباشر للشرطة العسكرية. هذه الصفحة لتسجيل مخالفات عساكر القطاع: السبب، القيمة، الإجراء، وهل تم التنفيذ.</p></header>
 <section className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><div className="rounded-[28px] border border-white/[.07] p-5"><div className="relative"><Search className="absolute right-4 top-1/2 -translate-y-1/2 text-zinc-700" size={15}/><input className="ds-input pr-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن العسكري..."/></div><div className="mt-3 max-h-[520px] space-y-2 overflow-y-auto slim-scrollbar">{filtered.map(r=><button key={r.id} onClick={()=>setRosterId(r.id)} className={`w-full rounded-[16px] border p-3 text-right ${rosterId===r.id?"border-[#b96f62]/30 bg-[#b96f62]/8":"border-white/[.055] bg-black/15"}`}><p className="font-black text-zinc-300">{r.name}</p><p className="mt-1 text-[10px] text-zinc-700">{getResolvedRank(r)} • {r.job_code} • Copy {r.copy_id}</p></button>)}</div></div>
 <div className="rounded-[28px] border border-white/[.07] p-5"><h2 className="text-2xl font-black">{person?.name||"اختر العسكري"}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-xs font-black text-zinc-600">السبب</span><textarea className="ds-input min-h-24" value={reason} onChange={e=>setReason(e.target.value)} placeholder="اكتب المخالفة بوضوح..."/></label><label><span className="mb-2 block text-xs font-black text-zinc-600">القيمة</span><input className="ds-input" value={value} onChange={e=>setValue(e.target.value)} placeholder="مثال: 50,000 أو إنذار"/></label><label><span className="mb-2 block text-xs font-black text-zinc-600">الإجراء</span><input className="ds-input" value={action} onChange={e=>setAction(e.target.value)} placeholder="الإجراء المتخذ"/></label><label className="sm:col-span-2"><span className="mb-2 block text-xs font-black text-zinc-600">الإثبات / الرابط (اختياري)</span><input className="ds-input" value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="رابط رسالة أو إثبات"/></label><label className="sm:col-span-2 flex items-center justify-between rounded-[16px] border border-white/[.06] p-4"><span><b className="block text-sm text-zinc-300">هل تم تنفيذ الإجراء؟</b><small className="text-zinc-700">يمكن تحديث الحالة لاحقًا من قاعدة البيانات عند الحاجة.</small></span><button type="button" onClick={()=>setExecuted(v=>!v)} className={`rounded-full px-4 py-2 text-xs font-black ${executed?"bg-emerald-500/12 text-emerald-400":"bg-white/[.04] text-zinc-600"}`}>{executed?"تم التنفيذ":"لم ينفذ"}</button></label></div><button onClick={save} disabled={!person||!reason.trim()||!action.trim()||saving} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-[16px] bg-[#b96f62] p-4 font-black text-white disabled:opacity-40">{saving?<Loader2 className="animate-spin" size={17}/>:<AlertTriangle size={17}/>} تسجيل المخالفة</button>{message&&<p className="mt-3 text-xs text-zinc-500">{message}</p>}</div></section>
 <section className="overflow-hidden rounded-[28px] border border-white/[.07]"><div className="border-b border-white/[.06] p-5"><h2 className="font-black">آخر المخالفات</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-right text-xs"><thead><tr className="text-zinc-700"><th className="px-5 py-3">العسكري</th><th className="px-4 py-3">السبب</th><th className="px-4 py-3">القيمة</th><th className="px-4 py-3">الإجراء</th><th className="px-4 py-3">التنفيذ</th><th className="px-4 py-3">سجلها</th><th className="px-4 py-3">التاريخ</th></tr></thead><tbody>{violations.map(v=><tr key={v.id} className="border-t border-white/[.05]"><td className="px-5 py-4 font-black text-zinc-300">{v.person_name}<span className="mr-2 font-mono text-[9px] text-zinc-700">{v.job_code}</span></td><td className="max-w-sm px-4 py-4 text-zinc-500">{v.reason}</td><td className="px-4 py-4 bronze-text">{v.value}</td><td className="px-4 py-4 text-zinc-500">{v.action}</td><td className="px-4 py-4">{v.executed?<span className="inline-flex items-center gap-1 text-emerald-400"><CheckCircle2 size={12}/> نعم</span>:<span className="inline-flex items-center gap-1 text-red-400"><XCircle size={12}/> لا</span>}</td><td className="px-4 py-4 text-zinc-600">{v.recorded_by_name}<br/><span className="text-[9px] text-zinc-700">{v.recorded_by_title}</span></td><td className="px-4 py-4 text-zinc-700" dir="ltr">{new Date(v.created_at).toLocaleDateString("ar-SA")}</td></tr>)}</tbody></table></div></section>
 </div>
}
